version: '3.8'

services:
  web:
    # Construire l'image à partir du Dockerfile dans le répertoire courant
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data
      - ./data_history:/app/data_history
